version: "3.9"

services:
  db:
    build: ./Database
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crawler
      MYSQL_USER: testUser
      MYSQL_PASSWORD: testPassword
    ports:
      - "3306:3306"
    volumes:
      - ./Database/mysqlData:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -prootpassword"]
      timeout: 5s
      interval: 10s
      retries: 10
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db

  backend:
    build: ./Backend/
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5077:5077"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "server=db;database=crawler;user=testUser;password=testPassword"
      MYSQL_HOST: db
      MYSQL_DATABASE: crawler
      MYSQL_USER: testUser
      MYSQL_PASSWORD: testPassword
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z db 3306"]
      interval: 10s
      retries: 10
    

  migration:
    build:
      dockerfile: ./Infrastructure/Dockerfile
      context: ./Backend/
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: crawler
      MYSQL_USER: testUser
      MYSQL_PASSWORD: testPassword
    
    entrypoint: "dotnet ef database update --project Infrastructure/Infrastructure.csproj --startup-project Api/Api.csproj --context Infrastructure.Persistence.Contexts.CrawlerDbContext"

  frontend:
    build: ./Client/
    ports:
      - "8083:80"
    depends_on:
      - backend
    

volumes:
  mysqlData:

